// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusalaGatewaysSysAdmin.Models;

#nullable disable

namespace MusalaGatewaysSysAdmin.Migrations
{
    [DbContext(typeof(GatewaysSysAdminDBContext))]
    partial class GatewaysSysAdminDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MusalaGatewaysSysAdmin.Models.Gateway", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaxClientNumber")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Gateway");
                });

            modelBuilder.Entity("MusalaGatewaysSysAdmin.Models.PeripheralDevice", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("DeviceVendor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DtDeviceCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("GatewayID")
                        .HasColumnType("int");

                    b.Property<bool>("Online")
                        .HasColumnType("bit");

                    b.Property<long>("UId")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("GatewayID");

                    b.ToTable("PeripheralDevice");
                });

            modelBuilder.Entity("MusalaGatewaysSysAdmin.Models.PeripheralDevice", b =>
                {
                    b.HasOne("MusalaGatewaysSysAdmin.Models.Gateway", null)
                        .WithMany("LsPeripheralDevices")
                        .HasForeignKey("GatewayID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MusalaGatewaysSysAdmin.Models.Gateway", b =>
                {
                    b.Navigation("LsPeripheralDevices");
                });
#pragma warning restore 612, 618
        }
    }
}
